Сделал /1-module/1-task/
js-tasks-ru/jsbasic-20221114_vladislav658 pull request #4
Opened 2022-11-21 15:19 UTC by Vladislav03111971

2022-11-21 15:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-22 12:31 UTC, SinimaWath requested changes

2022-11-22 12:31 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  factor = 1;
`let factor = 1`;

2022-11-22 12:31 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  } else {
Пустой if это плохой тон:

```
if (n == 0 || n == 1) {
  return factor;
}

for ( i = 1; i <= n; i++) {
      factor = factor * i;
}

return factor
```

2022-11-23 06:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-23 10:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-23 11:40 UTC, SinimaWath requested changes

2022-11-23 11:40 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
else тут лишние:
```
if (n == 0 || n == 1) {
  return factor;
}

for ( i = 1; i <= n; i++) {
      factor = factor * i;
}

return factor
```

alert можно убрать

2022-11-23 11:40 UTC, SinimaWath commented on 1-module/2-task/index.js
> +	  }
- Проверку на пробел, можно заменить на `name.includes(' ')`

2022-11-23 11:40 UTC, SinimaWath commented on 1-module/2-task/index.js
>  function isValid(name) {
Давай попробуем написать все условие в одну строчку:
`return <имя не null> && <длинна большек 3> && <нет пробелов>`

2022-11-23 12:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-23 12:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-23 13:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-23 15:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-24 11:13 UTC, SinimaWath requested changes

2022-11-24 11:13 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    return (factor);
Скобки тут лишние:
`return factor`

2022-11-24 11:13 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return (factor);
Тут тоже лишние скобки: 
`return factor`

2022-11-24 11:13 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Так как результат у тебя и так boolean, нет необходимости в if:
`return name !== null && name.length > 3 && !name.includes(" ")`

2022-11-24 11:13 UTC, SinimaWath commented on 1-module/3-task/index.js
> +	return (false);
Проверку можно упростить и убрать alert:
```
if (!str) {
  return str;
}
```

2022-11-24 11:13 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
- Можно написать без else
- Можно без временной переменной:
```
if (!str) {
  return str;
}

return str.charAt(0).toUpperCase() + str.substring(1)
```

2022-11-24 11:13 UTC, SinimaWath commented on 1-module/4-task/index.js
> +      return (false);
Результат операции и так boolean, поэтому if не нужен:
`return strValidUpper.includes("1XBET") || strValidUpper.includes("XXX")`

2022-11-25 05:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-25 05:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-25 05:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-25 05:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-25 06:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-25 09:28 UTC, SinimaWath approved these changes

2022-11-25 09:28 UTC, merged