Сделал /2-module/1-task/
js-tasks-ru/jsbasic-20221114_vladislav658 pull request #5
Opened 2022-11-26 11:48 UTC by Vladislav03111971

2022-11-26 11:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-26 12:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-26 13:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-27 10:09 UTC, SinimaWath requested changes

2022-11-27 10:09 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    calculator.first = a;
Давай используем this

2022-11-27 11:02 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-27 11:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-27 17:24 UTC, SinimaWath approved these changes

2022-11-27 17:25 UTC, merged