Сделал /3-module/1-task/
js-tasks-ru/jsbasic-20221114_vladislav658 pull request #6
Opened 2022-11-30 12:45 UTC by Vladislav03111971

2022-11-30 12:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-30 14:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-30 14:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-11-30 17:45 UTC, SinimaWath requested changes

2022-11-30 17:45 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    }
давай этот цикл for, попробуем переписать на map

2022-12-01 14:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-01 15:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-02 14:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-12-02 15:40 UTC, SinimaWath approved these changes

2022-12-02 15:41 UTC, merged